version: 2

defaults: &defaults
  working_directory: ~/repo
  machine:
      image: 'ubuntu-1604:201903-01'


jobs:
  build:
    <<: *defaults  
    steps:
      - checkout
      - run: npm install
      - run: npm run forever:stop
      - run: npm run forever:start
  test:
    <<: *defaults
    steps:
      - checkout
      - run: npm install
      - run: npm run forever:stop
      - run: npm run forever:start
      - run: npm run test
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test