jobs:
  build:
    steps:
      - run: npm install
      - run: npm run forever:stop
      - run: npm run forever:start
  test:
    steps:
      - run: npm run test
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test