jobs:
  build:
    machine:
      image: 'ubuntu-1604:201903-01'
    steps:
      - run: npm install
      - run: npm run forever:stop
      - run: npm run forever:start
  test:
    machine:
      image: 'ubuntu-1604:201903-01'
    steps:
      - run: npm run test
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test